import mvnctools.Controllers.Parsers.TensorFlowParser.Convolution
import mvnctools.Controllers.Parsers.TensorFlowParser.Placeholder
import mvnctools.Controllers.Parsers.TensorFlowParser.NoOp
import mvnctools.Controllers.Parsers.TensorFlowParser.ReLU
import mvnctools.Controllers.Parsers.TensorFlowParser.Eltwise
import mvnctools.Controllers.Parsers.TensorFlowParser.Pooling
import mvnctools.Controllers.Parsers.TensorFlowParser.LRN
import mvnctools.Controllers.Parsers.TensorFlowParser.BiasAdd
import mvnctools.Controllers.Parsers.TensorFlowParser.Concat
import mvnctools.Controllers.Parsers.TensorFlowParser.Reshape
import mvnctools.Controllers.Parsers.TensorFlowParser.FusedBatchNorm
import mvnctools.Controllers.Parsers.TensorFlowParser.Softmax
import mvnctools.Controllers.Parsers.TensorFlowParser.Identity
import mvnctools.Controllers.Parsers.TensorFlowParser.Slice
import mvnctools.Controllers.Parsers.TensorFlowParser.Pad
import mvnctools.Controllers.Parsers.TensorFlowParser.RealDiv

